# Generated by Django 6.0 on 2025-12-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('page_views', models.IntegerField()),
                ('active_users', models.IntegerField()),
                ('new_users', models.IntegerField()),
                ('sessions', models.IntegerField()),
                ('avg_session_duration', models.FloatField()),
                ('bounce_rate', models.FloatField()),
            ],
        ),
    ]
