# Generated by Django 6.0 on 2026-07-08 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('monthly_price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive plans are hidden from clients')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('daily_summaries', models.PositiveIntegerField(default=0)),
                ('daily_chat_messages', models.PositiveIntegerField(default=0)),
                ('daily_transcriptions', models.PositiveIntegerField(default=0)),
                ('max_chat_query_chars', models.PositiveIntegerField(default=0)),
                ('transcript_token_budget', models.PositiveIntegerField(default=0, help_text='Max transcript tokens sent per AI request (video token limit)')),
                ('max_transcription_seconds', models.PositiveIntegerField(default=0, help_text='Max audio duration transcribed per request')),
                ('storage_limit_mb', models.PositiveIntegerField(default=0)),
                ('max_file_size_mb', models.PositiveIntegerField(default=0)),
                ('max_note_chars', models.PositiveIntegerField(default=0)),
                ('max_notes_per_video', models.PositiveIntegerField(default=0)),
                ('max_screenshots_per_video', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(blank=True, help_text='After this moment the user falls back to the free plan', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_plans', to='plans.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('summary', 'Summary + key points'), ('chat', 'Chat message'), ('transcription', 'Audio transcription')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'kind', 'created_at'], name='plans_usage_user_id_8061e4_idx')],
            },
        ),
    ]
