# Generated by Django 6.0 on 2026-07-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_backfill_user_plans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='daily_transcriptions',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_transcription_seconds',
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='kind',
            field=models.CharField(choices=[('summary', 'Summary + key points'), ('chat', 'Chat message')], max_length=20),
        ),
    ]
