# Generated by Django 6.0 on 2025-12-18 18:52

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_url', models.URLField(unique=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('keypoints', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('slice_time', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VideoTranscripts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_video_id', models.CharField(max_length=30)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='VideoTranscriptTimeSlice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_url', models.URLField()),
                ('slice_time', models.FloatField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
