# Generated by Django 6.0 on 2025-12-18 18:52

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('path', models.CharField(max_length=255)),
                ('name', models.CharField(default='filename', max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('folder_id', models.UUIDField(default=0, editable=False)),
                ('size', models.FloatField(default=0, help_text='Size of the file in bytes', verbose_name='Size in bytes')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('user_id', models.UUIDField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
