from typing import Protocol


class ObjectStorageProvider(Protocol):
    def upload(self, key: str, body: bytes, content_type: str) -> str: ...
    def delete(self, key: str) -> None: ...
    def exists(self, key: str) -> bool: ...
